### ISSUE TITLE
any plans for packaging?

### ISSUE THREAD

**Issue by vaaaaanquish** [cod-sushi/alkana.py#3]
@cod-sushi Hi.

# Packaging
Are there any plans for packaging name by `alkana` ?
It is more common to be named by module.
```
pip install alkana
```

# Extension of the dictionary
Want to be able to add a dictionary? I want that feature.
for example: https://github.com/KEINOS/google-ime-user-dictionary-ja-en
ref: https://qiita.com/tame3_4dream/items/1dc46838747dc692d4da

---
Sorry if you are not interested in this project anymore. 
Feel free to say if you want a repair by PR:)
Thanks.

**Comment by vaaaaanquish** [comment]
I can help you with some work on PyPI. Please say anything:)

**Comment by zomysan** [comment]
The dictionary extension seems to be very useful. I also want that feature.
If you give a PR, I'll merge it!

Also I agree with the package name change.
In the next update, I will release it under the name "alkana(without ".py")".

Thank you for your offer!
