### ISSUE TITLE
追加辞書がたせません。

### ISSUE THREAD

**Issue by AlphaIru** [cod-sushi/alkana.py#8]
すいません、alkana.add_external_data('csvのパス')を入れても「Module 'alkana' has no 'add_external_data' member」　とエラーがでてきますが、どうしたら良いでしょうか？

環境はWindows 10です。

**Comment by yupix** [comment]
私も同様の現象に見舞われ確認したところ、pipに公開されているものには何故か`add_external_data`が存在しないみたいです。
githubには[こちら](https://github.com/cod-sushi/alkana.py/blob/821298245faee321f47341ae4d89ef4043f1ea4c/alkana/external_data.py#L8) に普通に存在するので更新してないだけだと思います。なので、以下のコマンドでgithubの方をインストールすることで解決できます。
`pip install git+https://github.com/cod-sushi/alkana.py`

※一応後学のためにコメント残しておきます。

**Comment by yupix** [comment]
それと、私だけの問題かもしれませんが、jtalk等で文字化けが発生しているような読み上げになる場合は [add_external_data](https://github.com/cod-sushi/alkana.py/blob/821298245faee321f47341ae4d89ef4043f1ea4c/alkana/external_data.py#L8)を以下のようにencodeを指定することで私の方では改善しました。
環境はwindows10, open_jtalk-1.09, hts_engine_API-1.10, 辞書などはopen_jtalk-1.09内臓のものを使用しています

```diff
def add_external_data(file_path):
    external_data = {}
-    with open(file_path, 'r') as f:
+    with open(file_path, 'r', encoding="utf-8") as f:
        for x in f:
            x = x.strip().split(',')
            external_data[x[0].lower()] = x[1]
    data.update(external_data)
```

**Comment by zomysan** [comment]
こちらyupix氏の仰るとおり、当方の作業漏れによるものです。
ご不便をおかけしており申し訳ありません。近々作業します！
問題の報告および解決策の提示、ありがとうございます。

**Comment by zomysan** [comment]
add_external_dataを含んだバージョンを `alkana@0.0.3` としてPyPIにリリースしました。
@yupix 氏に指摘いただいた追加辞書のエンコーディングについても、引数として指定できるよう追加いたしました。
